### ISSUE TITLE
run hello world in gradle

### ISSUE THREAD

**Issue by axthosarouris** [axthosarouris/kourafexala#4]
Description:

1.  Checkout the branch "hello test" locally 
2a.  If on linux run ./gradlew build and verify that it builds
2b. If on Windows run gradlew.bat buld and verify that it builds.
3.  Check the file HelloTest file and  try to run the test from your IDE
3.  Add any questions you may have as comments in the PR 
4.  When there are no unanswered questions approve PR.

**Comment by stellamaro** [comment]
Everything can be built and run. Some questions I have:

The `HelloTest` tests the `greetings()` method, which is a straightforward string. 
1. What if we had more complicated operations happening in a method?
2. Do we need to have specific "test data" that we know exactly what we expect?
3. We need some `main()` method in the `Hello` class, right? I understand that this code was only for testing if the tests work. In a normal scenario code, we'll have a `main()` method that will do things and multiple tests for some if not all the other methods. Right?

**Comment by axthosarouris** [comment]
1. What if we had more complicated operations happening in a method?

Theoretically, each function takes an input and always produces the same output for the same input. We will cover more complicated tests later.  For now the important thing is to understand how the testing framework works.

2. Depending on the scenario, yes. Usually we should generate the data per test. We will cover this as well later.
3. Your intuituiton is right. We should always test (or as much as possible) from the "main" method, where "main" is the entrypoint  to our code
